### ISSUE TITLE
Messed up orientation on mobile devices

### ISSUE THREAD

**Issue by areebbeigh** [codeclubtbms/PoemHaven#1]
![screenshot_2017-09-01-19-56-29-028_com android chrome](https://user-images.githubusercontent.com/15276828/29974227-d6e894ac-8f4f-11e7-9c77-33d726266161.png)

**Comment by areebmajeed** [comment]
Will push responsive fixes soon :)

**Comment by areebmajeed** [comment]
The responsive fixes have been applied in the recent push. Closed.
